In [ ]:
import numpy as np

for i in range(3):
    print(f"\nMatrix {i+1}:")

    A = np.random.randint(-10, 11, (3,3))
    print(A)

    det = np.linalg.det(A)
    print("Determinant:", det)

    if det == 0:
        print("This matrix does not have an inverse because its determinant is 0.")
    else:
        A_inv = np.linalg.inv(A)
        print("Inverse:")
        print(A_inv)

        product = A @ A_inv
        print("A * A_inv:")
        print(np.round(product, 6))


Matrix 1:
[[ -6  -6  -3]
 [  9  -6  -5]
 [ -7   2 -10]]
Determinant: -1098.0
Inverse:
[[-0.06375228  0.06010929 -0.01092896]
 [-0.11384335 -0.03551913  0.05191257]
 [ 0.02185792 -0.04918033 -0.08196721]]
A * A_inv:
[[ 1. -0.  0.]
 [ 0.  1.  0.]
 [ 0. -0.  1.]]

Matrix 2:
[[ 6  1 -1]
 [-4 -1  2]
 [ 8 -6  7]]
Determinant: 41.999999999999986
Inverse:
[[ 0.11904762 -0.02380952  0.02380952]
 [ 1.04761905  1.19047619 -0.19047619]
 [ 0.76190476  1.04761905 -0.04761905]]
A * A_inv:
[[ 1.  0. -0.]
 [ 0.  1.  0.]
 [-0. -0.  1.]]

Matrix 3:
[[ 4 -7  0]
 [ 8  1  9]
 [-6 -9  6]]
Determinant: 1062.0
Inverse:
[[ 0.0819209   0.03954802 -0.05932203]
 [-0.0960452   0.02259887 -0.03389831]
 [-0.06214689  0.07344633  0.05649718]]
A * A_inv:
[[ 1.  0.  0.]
 [ 0.  1. -0.]
 [ 0.  0.  1.]]
